version: "3.3"

services:
  redis:
    container_name: wwf_redis
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
  celery_worker:
    container_name: wwf_celery_worker
    build:
      context: ..
      dockerfile: ./docker/celery_worker/Dockerfile
    command: celery worker -A config -l info
    volumes:
      - ..:/code
    depends_on:
      - redis
  web:
    container_name: wwf_web
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command: ./docker/web_entrypoint_dev.sh
    environment:
      - ENVIRONMENT=development
    ports:
      - 8000:8000
    volumes:
      - ..:/code
    depends_on:
      - celery_worker
      - redis
