# Generated by Django 3.0 on 2019-12-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
