# Generated by Django 3.2.5 on 2021-07-25 16:48

from django.db import migrations, models
import rooms.models
import rooms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=rooms.models.video_location, validators=[rooms.validators.validate_video_extension]),
        ),
    ]
