# Generated by Django 3.0 on 2019-12-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
