version: '3.3'


services:
  redis:
    container_name: wwf_redis
    image: redis
    ports:
      - 6379:6379
  celery_worker:
    container_name: wwf_celery_worker
    build: .
    command: celery worker -A config -l info
    volumes:
      - .:/code
    depends_on:
      - redis
  web:
    container_name: wwf_web
    build: .
    command: ./web_entrypoint.sh
    environment:
      - ENVIRONMENT=development
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - celery_worker
      - redis
