version: '3.3'


services:
  redis:
    image: redis
    ports:
      - 6379:6379
  celery_worker:
    build: .
    command: celery worker -A config -l info
    depends_on:
      - redis
  web:
    build: .
    command: ./web_entrypoint.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - celery_worker
      - redis
