version: "3.3"

services:
  redis:
    container_name: wwf_redis
    image: redis
    ports:
      - 6379:6379
  celery_worker:
    container_name: wwf_celery_worker
    build:
      context: .
      dockerfile: ./celery_worker/Dockerfile
    command: celery worker -A config -l info
    volumes:
      - ./media:/code/media
    depends_on:
      - redis
  web:
    container_name: wwf_web
    build: .
    command: ./web_entrypoint.sh
    env_file:
      - ./config/settings/.env
    ports:
      - 8000:8000
    volumes:
      - ./static_root:/code/static_root
      - ./media:/code/media
    depends_on:
      - celery_worker
      - redis
      - db
  db:
    container_name: wwf_db
    image: postgres
    env_file:
      - ./config/settings/.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  proxy:
    image: nginx:alpine
    container_name: wwf_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./static_root:/var/www/static_root
      - ./media:/var/www/media
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web

volumes:
  postgres_data:
