version: '3.3'


services:
  redis:
    container_name: wwf_redis
    image: redis
    ports:
      - 6379:6379
  celery_worker:
    container_name: wwf_celery_worker
    build: .
    command: celery worker -A config -l info
    volumes:
      - .:/code
    depends_on:
      - redis
  web:
    container_name: wwf_web
    build: .
    command: ./web_entrypoint_prod.sh
    environment:
      - ENVIRONMENT=production
      - ALLOWED_HOSTS=*
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - celery_worker
      - redis
      - db
  db:
    container_name: wwf_db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
