---
- hosts: all
  vars:
    project_name: watch-with-friends
    repo_name: fly1ngDream/watch-with-friends
    webpack_dir: ~/{{ project_name }}/django/webpack
  tasks:
  - name: Dependencies
    tags: apt
    apt: cache_valid_time=3600 name={{ packages }}
    become: yes
    vars:
      packages:
        - python3
        - python-pip
        - python3-pip
        - python3-setuptools
        - docker
        - docker-compose
  - name: Clone repo
    tags: deploy
    git:
      repo: https://github.com/{{ repo_name }}
      update: yes
      force: yes
      dest: ~/{{ project_name }}
  - name: Install npm deps
    tags: deploy
    shell: npm install
    args:
      chdir: "{{ webpack_dir }}"
  - name: Build webpack bundles
    tags: deploy
    shell: npm run build
    args:
      chdir: "{{ webpack_dir }}"
  - name: Stop docker
    tags: deploy
    become: yes
    shell: docker-compose down
    args:
      chdir: /home/yevhens/{{ project_name }}/django
  - name: Run docker
    tags: deploy
    become: yes
    shell: docker-compose up -d --build
    args:
      chdir: /home/yevhens/{{ project_name }}/django
