---
- hosts: all
  vars:
    project_name: watch-with-friends
    repo_name: fly1ngDream/watch-with-friends
  tasks:
  - name: Dependencies
    tags: apt
    apt: cache_valid_time=3600 name={{ packages }}
    become: yes
    vars:
      packages:
        - python3
        - python-pip
        - python3-pip
        - python3-setuptools
        - docker
        - docker-compose
  - name: Clone repo
    tags: deploy
    git:
      repo: https://github.com/{{ repo_name }}
      update: yes
      force: yes
      dest: ~/{{ project_name }}
  - name: Install npm deps
    tags: deploy
    shell: npm install
    args:
      chdir: ~/{{ project_name }}/django/webpack
  - name: Build webpack bundles
    tags: deploy
    shell: npm run build
    args:
      chdir: ~/{{ project_name }}/django/webpack
  # - name: Install poetry deps
  #   tags: deploy
  #   shell: poetry install
  #   args:
  #     chdir: ~/{{ project_name }}/django
  - name: Migrate db
    tags: deploy
    shell: poetry run python manage.py migrate
    args:
      chdir: ~/{{ project_name }}/django
  # - name: Collect static files
  #   tags: deploy
  #   shell: pipenv run python manage.py collectstatic --noinput
  #   args:
  #     chdir: ~/{{ project_name }}
  - name: Run docker
    tags: deploy
    become: yes
    shell: docker-compose up -d --build
    args:
      chdir: ~/{{ project_name }}/django
